### ISSUE TITLE
A couple of queries

### ISSUE THREAD

**Issue by peterhinch** [russhughes/ttgo-hershey-fonts#2]
Sorry for raising this as an issue but I am interested in your code and have a few comments and queries.

My experience is with bitmapped fonts rather than vectors, but I assumed that a primary benefit of vector fonts was that they are scalable at runtime. As far as I can see your code renders them at a fixed size. Why is this?

Secondly, how do you get from a published Hershey font file to a Python font? There doesn't seem to be a vector equivalent to my `font-to-py` utility.

Looking at your video, I'm impressed at the speed of rendering from files. I found rendering bitmapped file fonts too slow for anything except ePaper displays, and stopped using binary font files as a consequence. I guess the performance is a mark of the efficiency of vector formats. I find font files frozen as bytecode are extraordinarily RAM-efficient. However with the speed you're getting, files save the hassle of freezing code. With solutions to the two queries above, vector fonts look very interesting.

A final thought. I have a set of display drivers published as part of [nano-gui](https://github.com/peterhinch/micropython-nano-gui). These support a variety of display controllers. While they can be used with `nano-gui` and `micro-gui`, they can also be used stand-alone. All offer a class subclassed from `framebuf.FrameBuffer`, and therefore inherit basic graphics primitives. Hopefully sufficient for rendering vectors. If you provided a way to render your fonts to a `FrameBuffer` instance you would achieve automatic compatibility with a range of graphics hardware including OLED, ePaper, Sharp and TFT. Also including the TTGO which could be used for testing. Just a thought...

**Comment by russhughes** [comment]
> My experience is with bitmapped fonts rather than vectors, but I assumed that a primary benefit of vector fonts was that they are scalable at runtime. As far as I can see your code renders them at a fixed size. Why is this?

This repo was created in response to question's I was asked, so the examples are basic.  The TurtlePlotBot library that the code came from as well as the 'C' based st7789 driver support scaling.  

>Secondly, how do you get from a published Hershey font file to a Python font? There doesn't seem to be a vector equivalent to my font-to-py utility.

The https://github.com/russhughes/hershey-scripts repo has that code.

Much of this code was originally written when I was learning Python and working on a MicroPython version of the TurtlePlotBot that ran on an ESP8266.  It was written as a learning experience and to fill the requirements of that project.  I don't think anyone has expressed an interest in having a framebuffer version so I haven't written one.

**Comment by peterhinch** [comment]
Thanks for clarifying.
